import '//code.jquery.com/jquery-1.11.0.min.js'
   import      '//code.jquery.com/jquery-migrate-1.2.1.min.js' 
   import 'https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js'    
   import '/js/slider.js'
  import './js/menu.js'